name: console_markdown
description: A console markdown for formatting and color, using chalk as a dependency. No setup required, quick and easy to use.
version: 0.0.2
repository: https://github.com/DrafaKiller/ConsoleMarkdown-dart
issue_tracker: https://github.com/DrafaKiller/ConsoleMarkdown-dart/issues

environment:
  sdk: '>=2.18.1 <3.0.0'

dependencies: 
  chalkdart: ^2.0.8
  marked: ^0.2.5

dev_dependencies:
  lints: ^2.0.0
